"""Initial migration

Revision ID: 7e323dcdb15d
Revises: None
Create Date: 2026-06-13 21:22:12.420475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e323dcdb15d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicacao',
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('subtitulo', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ano_publicacao', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('issn_isbn', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publicacao_id'), 'publicacao', ['id'], unique=False)
    op.create_index(op.f('ix_publicacao_titulo'), 'publicacao', ['titulo'], unique=False)
    op.create_table('usuario',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('nome_completo', sa.String(), nullable=True),
    sa.Column('orcid_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_orcid_id'), 'usuario', ['orcid_id'], unique=True)
    op.create_table('log_evento',
    sa.Column('tipo_evento', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_evento', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('entidade_tipo', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_evento_id'), 'log_evento', ['id'], unique=False)
    op.create_table('vaga',
    sa.Column('publicacao_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_total', sa.Integer(), nullable=False),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publicacao_id'], ['publicacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaga_id'), 'vaga', ['id'], unique=False)
    op.create_table('versao',
    sa.Column('publicacao_id', sa.Integer(), nullable=True),
    sa.Column('numero_versao', sa.String(), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.Column('caminho_arquivo_s3', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publicacao_id'], ['publicacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versao_id'), 'versao', ['id'], unique=False)
    op.create_table('compra',
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('vaga_id', sa.Integer(), nullable=True),
    sa.Column('data_compra', sa.DateTime(), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('mp_preference_id', sa.String(), nullable=True),
    sa.Column('id_pagamento_mp', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['vaga_id'], ['vaga.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compra_id'), 'compra', ['id'], unique=False)
    op.create_index(op.f('ix_compra_mp_preference_id'), 'compra', ['mp_preference_id'], unique=False)
    op.create_table('autor_publicacao',
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('publicacao_id', sa.Integer(), nullable=True),
    sa.Column('compra_id', sa.Integer(), nullable=True),
    sa.Column('funcao', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], ),
    sa.ForeignKeyConstraint(['publicacao_id'], ['publicacao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autor_publicacao_id'), 'autor_publicacao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autor_publicacao_id'), table_name='autor_publicacao')
    op.drop_table('autor_publicacao')
    op.drop_index(op.f('ix_compra_mp_preference_id'), table_name='compra')
    op.drop_index(op.f('ix_compra_id'), table_name='compra')
    op.drop_table('compra')
    op.drop_index(op.f('ix_versao_id'), table_name='versao')
    op.drop_table('versao')
    op.drop_index(op.f('ix_vaga_id'), table_name='vaga')
    op.drop_table('vaga')
    op.drop_index(op.f('ix_log_evento_id'), table_name='log_evento')
    op.drop_table('log_evento')
    op.drop_index(op.f('ix_usuario_orcid_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_publicacao_titulo'), table_name='publicacao')
    op.drop_index(op.f('ix_publicacao_id'), table_name='publicacao')
    op.drop_table('publicacao')
    # ### end Alembic commands ###